using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CafePOS.Api.Migrations
{
    /// <summary>
    /// Snapshot-only migration. Up/Down are deliberately EMPTY.
    ///
    /// Merging the aashish branch brought its own CafePosDbContextModelSnapshot.cs, which
    /// knows about MenuPdf but not about the Offers work, MenuCategory.SortOrder or
    /// OrderAppliedOffer that landed in parallel on main. A snapshot generated from either
    /// side alone is wrong, and the two cannot be hand-merged safely — the branches were
    /// even generated by different EF tooling (ToTable("X") vs ToTable("X", (string)null)),
    /// so the conflict spans the whole file.
    ///
    /// So the snapshot is regenerated from the merged model, and this migration is what
    /// carries it. Its generated Up() wanted to CREATE Offers, OfferMenuItems and
    /// OrderAppliedOffer and ADD SortOrder / AppliedOfferTitle / OfferDiscountAmount —
    /// every one of which already exists, created by AddOffers, AddOfferComboPrice and
    /// AddMenuCategorySortOrderAndOrderAppliedOffer. Running that body would fail on any
    /// database those migrations have touched, which is all of them.
    ///
    /// Left non-empty, this is the failure mode from before: the build succeeds, the
    /// container starts, and it dies applying migrations — or worse, boots and then throws
    /// PendingModelChangesWarning because the snapshot never matched the model.
    /// </summary>
    public partial class SyncSnapshotAfterAashishMerge : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty — see the class summary.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty — see the class summary.
        }
    }
}
