using CafePOS.Api.Domain;
using CafePOS.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;

namespace CafePOS.Api.Data;

/// <summary>
/// Optional, Development-only demo data for the Attendance / Payroll / Payslip screens.
///
/// Deliberately NOT part of <see cref="SeedData"/>: that file seeds catalog/config only
/// and documents that transactional data always starts empty. This is throwaway data for
/// looking at the HR UI with something in it, so it lives behind its own opt-in config
/// switch (<c>DemoData:SeedHrForTenantSlug</c>) and can be removed again in one flip
/// (<c>DemoData:PurgeHrDemo</c>).
///
/// Every row it writes is traceable back to here: staff carry <see cref="DemoEmailDomain"/>
/// e-mails and the payroll run carries <see cref="DemoRunNote"/>, which is exactly what
/// the purge path matches on — nothing typed in by a real user is ever touched.
/// </summary>
public static class DemoHrSeedData
{
    public const string DemoEmailDomain = "@demo.local";
    public const string DemoRunNote = "Demo data — generated by DemoHrSeedData";

    private record DemoStaff(string Name, string Role, string Department, string Designation, decimal BasicSalary, string Phone, string Account, string Ifsc);

    private static readonly DemoStaff[] Roster =
    [
        new("Aarav Sharma",  "Barista",        "Front of House", "Senior Barista",  22000m, "9820011223", "5011002233445", "HDFC0001234"),
        new("Diya Patel",    "Cashier",        "Front of House", "Cashier",         18000m, "9820044556", "5011002233446", "HDFC0001234"),
        new("Kabir Nair",    "Chef",           "Kitchen",        "Head Chef",       32000m, "9820077889", "5011002233447", "ICIC0005678"),
        new("Meera Iyer",    "Server",         "Front of House", "Server",          16000m, "9820099001", "5011002233448", "ICIC0005678"),
        new("Rohan Verma",   "Kitchen Helper", "Kitchen",        "Kitchen Helper",  14000m, "9820022334", "5011002233449", "SBIN0009012"),
    ];

    public static void Apply(CafePosDbContext db, ILogger logger, string? tenantSlug, string? ownerEmail, bool purge)
    {
        var tenant = ResolveTenant(db, logger, tenantSlug, ownerEmail);
        if (tenant is null) return;

        if (purge)
        {
            Purge(db, logger, tenant.Id);
            return;
        }

        // Global query filters resolve to the DEFAULT tenant at startup (there's no request
        // to read a JWT from), so every read here must ignore them and filter by hand.
        if (db.AttendanceRecords.IgnoreQueryFilters().Any(a => a.TenantId == tenant.Id))
        {
            logger.LogInformation("DemoData: tenant '{Slug}' already has attendance rows — skipping demo seed.", tenant.Slug);
            return;
        }

        var settings = db.Settings.IgnoreQueryFilters().FirstOrDefault(s => s.TenantId == tenant.Id) ?? new CafeSettings();
        var today = DateOnly.FromDateTime(DateTime.UtcNow);
        var periodStart = new DateOnly(today.Year, today.Month, 1).AddMonths(-1);
        var periodEnd = periodStart.AddMonths(1).AddDays(-1);

        var staff = SeedStaff(db, tenant.Id);
        LinkSignedInOwnerToRoster(db, logger, tenant.Id, ownerEmail, staff);
        var loans = SeedLoans(db, tenant.Id, staff);
        var leaves = SeedLeave(db, tenant.Id, staff);
        SeedShiftsAndAttendance(db, tenant.Id, staff, periodStart, today.AddDays(-1));
        db.SaveChanges();

        SeedPaidPayrollRun(db, tenant.Id, staff, loans, leaves, settings, periodStart, periodEnd);
        db.SaveChanges();

        logger.LogWarning(
            "DemoData: seeded {StaffCount} demo staff + attendance ({From} → {To}) and a PAID payroll run for {Period:yyyy-MM} into tenant '{Slug}'. "
            + "Set DemoData:PurgeHrDemo=true to remove it again.",
            staff.Count, periodStart, today.AddDays(-1), periodStart, tenant.Slug);
    }

    /// <summary>
    /// Either identifier works — the cafe's slug (shown on the Cafe Profile screen) or the
    /// e-mail you sign in with, because the slug isn't something anyone has memorised.
    /// Neither set means the whole feature stays off.
    /// </summary>
    private static Tenant? ResolveTenant(CafePosDbContext db, ILogger logger, string? tenantSlug, string? ownerEmail)
    {
        if (!string.IsNullOrWhiteSpace(ownerEmail))
        {
            // AppUser is deliberately not tenant-filtered (see its TenantId doc comment),
            // so an e-mail lookup works here at startup without IgnoreQueryFilters.
            var user = db.Users.FirstOrDefault(u => u.Email == ownerEmail);
            if (user is null)
            {
                logger.LogWarning("DemoData: no login found for '{Email}' — nothing seeded.", ownerEmail);
                return null;
            }
            var byUser = db.Tenants.FirstOrDefault(t => t.Id == user.TenantId);
            if (byUser is null) logger.LogWarning("DemoData: login '{Email}' points at tenant {TenantId}, which no longer exists.", ownerEmail, user.TenantId);
            return byUser;
        }

        if (string.IsNullOrWhiteSpace(tenantSlug)) return null;

        var tenant = db.Tenants.FirstOrDefault(t => t.Slug == tenantSlug);
        if (tenant is null)
        {
            logger.LogWarning(
                "DemoData: no tenant with slug '{Slug}' — nothing seeded. Known slugs: {Known}.",
                tenantSlug, string.Join(", ", db.Tenants.Select(t => t.Slug).Take(20)));
        }
        return tenant;
    }

    // ---------- Staff ----------

    private static List<StaffMember> SeedStaff(CafePosDbContext db, int tenantId)
    {
        var existing = db.Staff.IgnoreQueryFilters().Where(s => s.TenantId == tenantId && s.Email!.EndsWith(DemoEmailDomain)).ToList();
        if (existing.Count > 0) return existing;

        var joined = DateTime.UtcNow.AddMonths(-14);
        var staff = Roster.Select((r, i) => new StaffMember
        {
            TenantId = tenantId,
            Name = r.Name,
            Role = r.Role,
            Email = $"{r.Name.Split(' ')[0].ToLowerInvariant()}.{r.Name.Split(' ')[1].ToLowerInvariant()}{DemoEmailDomain}",
            Phone = r.Phone,
            Status = StaffStatus.Active,
            JoinedAt = joined.AddDays(i * 23),
            Department = r.Department,
            Designation = r.Designation,
            SalaryType = SalaryType.Monthly,
            BasicSalary = r.BasicSalary,
            HourlyRate = Math.Round(r.BasicSalary / 30m / 8m, 2),
            BankAccountNumber = r.Account,
            BankIfsc = r.Ifsc,
            BankName = r.Ifsc.StartsWith("HDFC") ? "HDFC Bank" : r.Ifsc.StartsWith("ICIC") ? "ICICI Bank" : "State Bank of India",
            Pan = $"ABCDE{1000 + i}F",
        }).ToList();

        db.Staff.AddRange(staff);
        db.SaveChanges(); // ids are needed by everything below
        return staff;
    }

    /// <summary>
    /// My Attendance and My Payslips resolve their data through StaffMember.UserId ==
    /// the caller's user id, and hard-fail with "This login has no linked staff roster
    /// entry" when there isn't one — an owner who registered a cafe has no roster row by
    /// default. So the first demo roster entry is adopted by the tenant's owner login and
    /// renamed to them; without this the two self-service screens stay unreachable no
    /// matter how much attendance data exists.
    /// </summary>
    private static void LinkSignedInOwnerToRoster(CafePosDbContext db, ILogger logger, int tenantId, string? ownerEmail, List<StaffMember> staff)
    {
        if (staff.Count == 0) return;

        // Prefer the exact login the seed was aimed at; otherwise the cafe's owner.
        var owner = (string.IsNullOrWhiteSpace(ownerEmail) ? null : db.Users.FirstOrDefault(u => u.Email == ownerEmail))
            ?? db.Users.Where(u => u.TenantId == tenantId && !u.IsPlatformAdmin)
                .OrderBy(u => u.Role == AppRole.Owner ? 0 : 1).ThenBy(u => u.Id)
                .FirstOrDefault();
        if (owner is null)
        {
            logger.LogWarning("DemoData: tenant has no login to attach the roster to — My Attendance / My Payslips will stay empty.");
            return;
        }

        // Their own roster entry already exists (real or from an earlier run) — leave it alone.
        if (db.Staff.IgnoreQueryFilters().Any(s => s.UserId == owner.Id)) return;

        var mine = staff[0];
        mine.UserId = owner.Id;
        mine.Name = owner.Name;
        mine.Phone = owner.Phone ?? mine.Phone;
        db.SaveChanges();
        logger.LogInformation("DemoData: linked roster entry '{Name}' to login {Email} for the self-service screens.", mine.Name, owner.Email);
    }

    // ---------- Loans / leave ----------

    private static List<StaffLoan> SeedLoans(CafePosDbContext db, int tenantId, List<StaffMember> staff)
    {
        var chef = staff[2];
        var helper = staff[4];
        var loans = new List<StaffLoan>
        {
            new()
            {
                TenantId = tenantId, StaffId = chef.Id, StaffName = chef.Name, Type = LoanType.Loan,
                PrincipalAmount = 30000m, MonthlyDeduction = 2500m, OutstandingBalance = 22500m,
                StartDate = DateOnly.FromDateTime(DateTime.UtcNow.AddMonths(-4)),
                Reason = "Family medical expense", ApprovedByName = "Owner",
            },
            new()
            {
                TenantId = tenantId, StaffId = helper.Id, StaffName = helper.Name, Type = LoanType.Advance,
                PrincipalAmount = 6000m, MonthlyDeduction = 1000m, OutstandingBalance = 4000m,
                StartDate = DateOnly.FromDateTime(DateTime.UtcNow.AddMonths(-2)),
                Reason = "Salary advance", ApprovedByName = "Owner",
            },
        };
        db.StaffLoans.AddRange(loans);
        return loans;
    }

    private static List<LeaveRequest> SeedLeave(CafePosDbContext db, int tenantId, List<StaffMember> staff)
    {
        var lastMonth = DateOnly.FromDateTime(DateTime.UtcNow).AddMonths(-1);
        var server = staff[3];
        var cashier = staff[1];
        var leaves = new List<LeaveRequest>
        {
            new()
            {
                TenantId = tenantId, StaffId = server.Id, StaffName = server.Name, Type = LeaveType.Paid,
                StartDate = new DateOnly(lastMonth.Year, lastMonth.Month, 12), EndDate = new DateOnly(lastMonth.Year, lastMonth.Month, 13),
                Status = LeaveRequestStatus.Approved, Reason = "Family function", ReviewedByName = "Owner", ReviewedAt = DateTime.UtcNow.AddDays(-30),
            },
            new()
            {
                TenantId = tenantId, StaffId = cashier.Id, StaffName = cashier.Name, Type = LeaveType.Unpaid,
                StartDate = new DateOnly(lastMonth.Year, lastMonth.Month, 20), EndDate = new DateOnly(lastMonth.Year, lastMonth.Month, 20),
                Status = LeaveRequestStatus.Approved, Reason = "Personal", ReviewedByName = "Owner", ReviewedAt = DateTime.UtcNow.AddDays(-25),
            },
            new()
            {
                TenantId = tenantId, StaffId = staff[0].Id, StaffName = staff[0].Name, Type = LeaveType.Sick,
                StartDate = DateOnly.FromDateTime(DateTime.UtcNow).AddDays(3), EndDate = DateOnly.FromDateTime(DateTime.UtcNow).AddDays(4),
                Status = LeaveRequestStatus.Pending, Reason = "Fever — doctor advised rest",
            },
        };
        db.LeaveRequests.AddRange(leaves);
        return leaves;
    }

    // ---------- Shifts + attendance ----------

    /// <summary>
    /// Sundays are the weekly off (no shift, no record). Absent days are represented the
    /// way the app itself defines them — a scheduled Shift with no AttendanceRecord against
    /// it — because AttendanceRecord.Status never stores Absent (see its doc comment).
    /// </summary>
    private static void SeedShiftsAndAttendance(CafePosDbContext db, int tenantId, List<StaffMember> staff, DateOnly from, DateOnly to)
    {
        for (var s = 0; s < staff.Count; s++)
        {
            var member = staff[s];
            var dayIndex = 0;
            for (var date = from; date <= to; date = date.AddDays(1))
            {
                if (date.DayOfWeek == DayOfWeek.Sunday) continue;
                dayIndex++;

                var shiftStart = date.ToDateTime(new TimeOnly(9, 0));
                db.Shifts.Add(new Shift { TenantId = tenantId, StaffId = member.Id, StartsAt = shiftStart, EndsAt = shiftStart.AddHours(8) });

                // Staggered per staff member so the roster doesn't march in lockstep.
                var slot = (dayIndex + s * 3) % 12;
                if (slot == 4) continue; // absent: shift scheduled, nobody punched in

                var isLate = slot == 1;
                var isHalfDay = slot == 7;
                var hasOvertime = slot == 9;

                var punchIn = shiftStart.AddMinutes(isLate ? 25 : -4);
                var punchOut = isHalfDay ? shiftStart.AddHours(4) : shiftStart.AddHours(hasOvertime ? 9.5 : 8).AddMinutes(6);
                var breakMinutes = isHalfDay ? 0 : 30;
                var worked = (int)(punchOut - punchIn).TotalMinutes - breakMinutes;
                var overtime = Math.Max(0, worked - 8 * 60);

                db.AttendanceRecords.Add(new AttendanceRecord
                {
                    TenantId = tenantId,
                    StaffId = member.Id,
                    Date = date,
                    PunchInAt = punchIn,
                    PunchOutAt = punchOut,
                    BreakMinutes = breakMinutes,
                    WorkedMinutes = worked,
                    Status = isHalfDay ? AttendanceStatus.HalfDay : isLate ? AttendanceStatus.Late : AttendanceStatus.Present,
                    LateMinutes = isLate ? 15 : 0,
                    OvertimeMinutes = overtime,
                });
            }
        }
    }

    // ---------- Payroll ----------

    /// <summary>
    /// A finalized (Paid) run for last month, so My Payslips and the payslip PDF have
    /// something to show without anyone having to run the real generator first.
    ///
    /// The arithmetic below mirrors PayrollController's Monthly branch (every demo staff
    /// member is SalaryType.Monthly) and reuses the real StatutoryDeductionCalculator, but
    /// it is a copy, not the same code — the generator's version lives on private methods
    /// of the controller. Treat the real thing as the source of truth: generating a fresh
    /// run from the Payroll Runs screen is what exercises it.
    /// </summary>
    private static void SeedPaidPayrollRun(
        CafePosDbContext db,
        int tenantId,
        List<StaffMember> staff,
        List<StaffLoan> loans,
        List<LeaveRequest> leaves,
        CafeSettings settings,
        DateOnly periodStart,
        DateOnly periodEnd)
    {
        var attendance = db.AttendanceRecords.IgnoreQueryFilters()
            .Where(a => a.TenantId == tenantId && a.Date >= periodStart && a.Date <= periodEnd)
            .ToList();
        var shiftDates = db.Shifts.IgnoreQueryFilters()
            .Where(s => s.TenantId == tenantId)
            .Select(s => new { s.StaffId, s.StartsAt })
            .ToList();

        var periodDays = periodEnd.DayNumber - periodStart.DayNumber + 1;
        var monthRatio = periodDays / 30m;
        var run = new PayrollRun
        {
            TenantId = tenantId,
            PeriodStart = periodStart,
            PeriodEnd = periodEnd,
            Status = PayrollRunStatus.Paid,
            GeneratedAt = periodEnd.ToDateTime(new TimeOnly(18, 0)),
            GeneratedByName = "Owner",
            LockedAt = periodEnd.ToDateTime(new TimeOnly(18, 30)),
            PaidAt = periodEnd.ToDateTime(new TimeOnly(19, 0)),
            Notes = DemoRunNote,
        };

        foreach (var member in staff)
        {
            var mine = attendance.Where(a => a.StaffId == member.Id).ToList();
            var attended = mine.Where(a => a.WorkedMinutes.HasValue).Select(a => a.Date).ToHashSet();
            var presentDays = attended.Count;
            var lateDays = mine.Count(a => a.Status == AttendanceStatus.Late);
            var halfDays = mine.Count(a => a.Status == AttendanceStatus.HalfDay);
            var overtimeHours = mine.Sum(a => a.OvertimeMinutes) / 60.0;

            var myLeave = leaves.Where(l => l.StaffId == member.Id && l.Status == LeaveRequestStatus.Approved
                && l.StartDate <= periodEnd && l.EndDate >= periodStart).ToList();
            var leaveDates = new HashSet<DateOnly>();
            int paidLeaveDays = 0, unpaidLeaveDays = 0;
            foreach (var leave in myLeave)
            {
                var start = leave.StartDate > periodStart ? leave.StartDate : periodStart;
                var end = leave.EndDate < periodEnd ? leave.EndDate : periodEnd;
                var days = end.DayNumber - start.DayNumber + 1;
                if (leave.Type == LeaveType.Unpaid) unpaidLeaveDays += days; else paidLeaveDays += days;
                for (var d = start; d <= end; d = d.AddDays(1)) leaveDates.Add(d);
            }

            var scheduled = shiftDates.Where(s => s.StaffId == member.Id)
                .Select(s => DateOnly.FromDateTime(s.StartsAt))
                .Where(d => d >= periodStart && d <= periodEnd)
                .Distinct().ToList();
            var absentDays = scheduled.Count(d => !attended.Contains(d) && !leaveDates.Contains(d));

            var monthlyBasic = member.BasicSalary ?? 0;
            var perDayRate = monthlyBasic / 30m;
            var basePay = Math.Round(monthlyBasic * monthRatio, 2);
            var hourlyEquivalent = settings.StandardShiftHours > 0 ? perDayRate / settings.StandardShiftHours : 0;
            var overtimePay = Math.Round((decimal)overtimeHours * hourlyEquivalent * 1.5m, 2);
            var grossBeforeAllowances = basePay + overtimePay;

            var line = new PayrollLine
            {
                TenantId = tenantId,
                StaffId = member.Id,
                StaffName = member.Name,
                SalaryType = member.SalaryType,
                BasicSalary = basePay,
                HourlyRate = member.HourlyRate,
                PresentDays = presentDays,
                LateDays = lateDays,
                HalfDays = halfDays,
                AbsentDays = absentDays,
                PaidLeaveDays = paidLeaveDays,
                UnpaidLeaveDays = unpaidLeaveDays,
                OvertimeHours = overtimeHours,
                OvertimePay = overtimePay,
                Allowances = [],
                LeaveDeduction = Math.Round(unpaidLeaveDays * perDayRate, 2),
                LateDeduction = Math.Round(lateDays * perDayRate * 0.1m, 2),
                LoanDeduction = loans.Where(l => l.StaffId == member.Id).Sum(l => Math.Min(l.MonthlyDeduction, l.OutstandingBalance)),
                PfDeduction = StatutoryDeductionCalculator.Pf(basePay, StatutoryDeductionCalculator.MonthlyPfWageCeiling * monthRatio),
                EsicDeduction = StatutoryDeductionCalculator.Esic(grossBeforeAllowances, StatutoryDeductionCalculator.MonthlyEsicGrossCeiling * monthRatio),
                ProfessionalTaxDeduction = StatutoryDeductionCalculator.ProfessionalTax(
                    grossBeforeAllowances,
                    StatutoryDeductionCalculator.MonthlyProfessionalTaxThreshold * monthRatio,
                    StatutoryDeductionCalculator.MonthlyProfessionalTaxFlat * monthRatio),
                BankAccountNumberSnapshot = member.BankAccountNumber,
                BankIfscSnapshot = member.BankIfsc,
            };
            Finalize(line);
            run.Lines.Add(line);

            // The run is seeded as already Paid, and MarkPaid is what draws down a loan —
            // so the balances have to reflect this run's deduction or they'd read as unpaid.
            var remaining = line.LoanDeduction;
            foreach (var loan in loans.Where(l => l.StaffId == member.Id))
            {
                if (remaining <= 0) break;
                var take = Math.Min(remaining, loan.OutstandingBalance);
                loan.OutstandingBalance -= take;
                remaining -= take;
                if (loan.OutstandingBalance > 0) continue;
                loan.Status = LoanStatus.Closed;
                loan.ClosedAt = DateTime.UtcNow;
            }
        }

        db.PayrollRuns.Add(run);
    }

    /// <summary>Mirror of PayrollController.FinalizeLine — see SeedPaidPayrollRun's note.</summary>
    private static void Finalize(PayrollLine line)
    {
        line.AllowancesTotal = line.Allowances.Sum(a => a.Amount);
        line.GrossEarnings = line.BasicSalary + line.OvertimePay + line.AllowancesTotal;
        var nonLoan = line.LeaveDeduction + line.LateDeduction + line.PfDeduction + line.EsicDeduction + line.ProfessionalTaxDeduction;
        line.LoanDeduction = Math.Min(line.LoanDeduction, Math.Max(0, line.GrossEarnings - nonLoan));
        line.TotalDeductions = nonLoan + line.LoanDeduction;
        line.NetSalary = Math.Max(0, line.GrossEarnings - line.TotalDeductions);
    }

    // ---------- Purge ----------

    private static void Purge(CafePosDbContext db, ILogger logger, int tenantId)
    {
        var staffIds = db.Staff.IgnoreQueryFilters()
            .Where(s => s.TenantId == tenantId && s.Email!.EndsWith(DemoEmailDomain))
            .Select(s => s.Id).ToList();
        if (staffIds.Count == 0)
        {
            logger.LogInformation("DemoData: nothing to purge for tenant {TenantId}.", tenantId);
            return;
        }

        db.PayrollLines.RemoveRange(db.PayrollLines.IgnoreQueryFilters().Where(l => l.TenantId == tenantId && staffIds.Contains(l.StaffId)));
        db.PayrollRuns.RemoveRange(db.PayrollRuns.IgnoreQueryFilters().Where(r => r.TenantId == tenantId && r.Notes == DemoRunNote));
        db.StaffLoans.RemoveRange(db.StaffLoans.IgnoreQueryFilters().Where(l => l.TenantId == tenantId && staffIds.Contains(l.StaffId)));
        db.LeaveRequests.RemoveRange(db.LeaveRequests.IgnoreQueryFilters().Where(l => l.TenantId == tenantId && staffIds.Contains(l.StaffId)));
        db.AttendanceRecords.RemoveRange(db.AttendanceRecords.IgnoreQueryFilters().Where(a => a.TenantId == tenantId && staffIds.Contains(a.StaffId)));
        db.AttendanceLogs.RemoveRange(db.AttendanceLogs.IgnoreQueryFilters().Where(a => a.TenantId == tenantId && staffIds.Contains(a.StaffId)));
        db.Shifts.RemoveRange(db.Shifts.IgnoreQueryFilters().Where(s => s.TenantId == tenantId && staffIds.Contains(s.StaffId)));
        db.Staff.RemoveRange(db.Staff.IgnoreQueryFilters().Where(s => staffIds.Contains(s.Id)));
        db.SaveChanges();

        logger.LogWarning("DemoData: purged demo HR data ({Count} staff and everything hanging off them) from tenant {TenantId}.", staffIds.Count, tenantId);
    }
}
